### ISSUE TITLE
Error during maven build related to scala-maven-plugin

### ISSUE THREAD

**Issue by cronus42** [claudiacauli/CloudFORMAL#4]
When attempting to build master with install.sh I receive the following error:

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.2.4:compile (default-cli) on project CloudFORMAL: wrap: java.lang.reflect.InvocationTargetException: NullPointerException -> [Help 1]

error: java.lang.NullPointerException
        at scala.tools.nsc.classpath.JrtClassPath$.apply(DirectoryClassPath.scala:144)
        at scala.tools.util.PathResolver$Calculated$.jrt(PathResolver.scala:271)
        at scala.tools.util.PathResolver$Calculated$.basis(PathResolver.scala:260)
        at scala.tools.util.PathResolver$Calculated$.containers$lzycompute(PathResolver.scala:273)
        at scala.tools.util.PathResolver$Calculated$.containers(PathResolver.scala:273)
        at scala.tools.util.PathResolver.containers(PathResolver.scala:289)
        at scala.tools.util.PathResolver.computeResult(PathResolver.scala:311)
        at scala.tools.util.PathResolver.result(PathResolver.scala:294)
        at scala.tools.nsc.backend.JavaPlatform.classPath(JavaPlatform.scala:30)
        at scala.tools.nsc.backend.JavaPlatform.classPath$(JavaPlatform.scala:29)
        at scala.tools.nsc.Global$GlobalPlatform.classPath(Global.scala:124)
        at scala.tools.nsc.Global.classPath(Global.scala:135)
        at scala.tools.nsc.Global$GlobalMirror.rootLoader(Global.scala:66)
        at scala.reflect.internal.Mirrors$Roots$RootClass.<init>(Mirrors.scala:307)
        at scala.reflect.internal.Mirrors$Roots.RootClass$lzycompute(Mirrors.scala:321)
        at scala.reflect.internal.Mirrors$Roots.RootClass(Mirrors.scala:321)
        at scala.reflect.internal.Mirrors$Roots$EmptyPackageClass.<init>(Mirrors.scala:330)
        at scala.reflect.internal.Mirrors$Roots.EmptyPackageClass$lzycompute(Mirrors.scala:336)
        at scala.reflect.internal.Mirrors$Roots.EmptyPackageClass(Mirrors.scala:336)
        at scala.reflect.internal.Mirrors$Roots.EmptyPackageClass(Mirrors.scala:276)
        at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:250)
        at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:73)
        at scala.tools.nsc.Global.rootMirror(Global.scala:71)
        at scala.tools.nsc.Global.rootMirror(Global.scala:43)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:286)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:286)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1585)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1205)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:47)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
        at scala.tools.nsc.Driver.process(Driver.scala:68)
        at scala.tools.nsc.Main.process(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
        at sbt.internal.inc.RawCompiler.getReporter$1(RawCompiler.scala:56)
        at sbt.internal.inc.RawCompiler.apply(RawCompiler.scala:77)
        at sbt_inc.SbtIncrementalCompiler.getCompiledBridgeJar(SbtIncrementalCompiler.java:220)
        at sbt_inc.SbtIncrementalCompiler.<init>(SbtIncrementalCompiler.java:79)
        at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:287)
        at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:109)
        at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:91)
        at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:554)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)

When running the jar I receive another error: 

java -Xmx1G -jar target/ExecCloudFORMAL.jar
Error: Could not find or load main class com.cloud.formal.Main

**Comment by claudiacauli** [comment]
Which java version is installed in the system? 
And do you have some version of Scala/SBT installed as well?  

Try `java -version` and `scala -version` (or `which sbt`, `sbt -version`)
 
 
I pushed some new commits that also included config changes to pom.xml, could you please try to build the last commit that I pushed?

In one of the latest commits (33b7f5a85d016fd47c97e569ced158e9b1220415) the pom.xml is configured to run scala-maven-plugin-4.4.0 and uses scala library 2.13.4 (I experienced issues myself when compiling from my system the code that was compiled with scala-maven-4.2.4). 
I think there could be incompatibility issues between scala 2.13.4 and required JDKs that I'm not handling well.

Thanks!
